### ISSUE TITLE
Hidden block shows instantly

### ISSUE THREAD

**Issue by JiangLong2019** [hlxsites/sunstar-foundation#120]
Hi @bosschaert, when I previewed the authored content, I found the Hidden block shows instantly then it was gone.

https://github.com/hlxsites/sunstar-foundation/assets/57093988/c4a74bcf-1d28-4aca-ad73-921326f02919

**Comment by bosschaert** [comment]
@JiangLong2019 could you please post the URL of that document?

**Comment by JiangLong2019** [comment]
@bosschaert here you go - https://main--sunstar-foundation--hlxsites.hlx.live/en/awards/aap
I think maybe we need to hide it on the higher layer or add "display:none" to the html tag directly.

**Comment by bosschaert** [comment]
I'll take a look, thanks!

**Comment by bosschaert** [comment]
Hi @JiangLong2019 I ran it through the debugger and found that the TOC block still loads the Apply button, even though it's not inside the TOC block any more in the worddoc (it's also not in the aap.md file). You can see it in this screenshot:
<img width="1840" alt="Screenshot 2024-01-18 at 12 26 29" src="https://github.com/hlxsites/sunstar-foundation/assets/226514/943a7335-094f-4dc6-a2ad-248bc0976de2">
Could it be that the TOC block loads too much?

The .md representation has the correct tables AFAICS:
<img width="843" alt="Screenshot 2024-01-18 at 12 28 21" src="https://github.com/hlxsites/sunstar-foundation/assets/226514/d6929e7e-15d4-4aeb-9b70-09095ac16df4">

**Comment by JiangLong2019** [comment]
@bosschaert TOC has not loaded the apply button, it just restructures the sections and adds some parent div for creating the layout. If it loads the button, the button will be shown above the TOC links.

<img width="745" alt="image" src="https://github.com/hlxsites/sunstar-foundation/assets/57093988/4011d0d4-3909-4837-bff5-3256e123f732">

I just had a test that the issue is gone after I removed the hidden-block.
https://bit.ly/3tYl8yD
