### ISSUE TITLE
Dentistry > Adult

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar-foundation#175]
Can you please adjust the spacing inside the custom columns component.

https://main--sunstar-foundation--hlxsites.hlx.page/dentistry/adult

![image](https://github.com/hlxsites/sunstar-foundation/assets/1226479/a1adf339-c79f-43ff-b96a-64ad518fa917)

FYI: @bosschaert @sdmcraft 

Not a blocker

**Comment by shrotia** [comment]
PR raised: https://github.com/hlxsites/sunstar-foundation/pull/199
