### ISSUE TITLE
Hero Banner component

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar-foundation#179]
There is a blank space in the hero banner component when the text is too small. The before element is inheriting its width from the parent so small text leads to this blank space section.

Like on this page:
https://main--sunstar-foundation--hlxsites.hlx.live/en/education/perio-link-night

You can set min-width to 150% on the before element.

![image](https://github.com/hlxsites/sunstar-foundation/assets/1226479/d476f66b-917e-438c-8d70-b8ec4abeecca)

FYI: @bosschaert @sdmcraft 

Not a blocker

**Comment by jindaliiita** [comment]
Didn't exactly got this issue.
@ehrro Can you please mention screen size also because its not reproducible at my end.

**Comment by ehrro** [comment]
If you open the page you can see that there is a blank space gap on the left side:

![image](https://github.com/hlxsites/sunstar-foundation/assets/1226479/591f3c22-2320-442a-8f30-88199404070e)

The reason there is a gap here is because the width of the before blue element is based on it's parent and if the parent is not wide enough it won't fill the gap until the end.

**Comment by jindaliiita** [comment]
> If you open the page you can see that there is a blank space gap on the left side:
> 
> ![image](https://private-user-images.githubusercontent.com/1226479/303294116-591f3c22-2320-442a-8f30-88199404070e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODgzOTEsIm5iZiI6MTcwNzM4ODA5MSwicGF0aCI6Ii8xMjI2NDc5LzMwMzI5NDExNi01OTFmM2MyMi0yMzIwLTQ0MmEtOGYzMC04ODE5OTQwNDA3MGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMTAyODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTA4ZmM4MDIyNmJjZDBkNDk0NWM3ZTg1YzRiNTc4ODIxN2JkYTQ3MGE4NzdmODczZTliZmU4NWQzZjYzOGFkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sLgpoZuIRk68DeRzmqPuGDTG5eJSFRh7KpEsi9xEZmY)
> 
> The reason there is a gap here is because the width of the before blue element is based on it's parent and if the parent is not wide enough it won't fill the gap until the end.

For me its not reproducible on any screen size. Can you please share browser and screen size ?
