### ISSUE TITLE
Migrate Varians from sunstar.com

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar-foundation#206]
Can you please migrate the following variants from sunstar.com:

1. Columns block:
- Flex start (this variant not needed if we can control it via markdown with vertical align in word)
- Native Image Sizes
- no padding

2. Containers
- Narrower

**Comment by shrotia** [comment]
@ehrro 

> Flex start 

The `flex-start` variant of columns block already exist ([code link](https://github.com/hlxsites/sunstar-foundation/blob/main/blocks/columns/columns.css#L555-L560))

> no padding

did you meant `no-padding` section ? As I didn't find no-padding variant at Columns block in sunstar.com ([code link](https://github.com/hlxsites/sunstar/blob/main/blocks/columns/columns.css))

> Narrower
I can see Narrower variant for Section already exist ([code link](https://github.com/hlxsites/sunstar-foundation/blob/main/styles/styles.css#L1077-L1087)), did you meant Narrower variant for some other block? please confirm

**Comment by shrotia** [comment]
> Native Image Sizes

PR raised: https://github.com/hlxsites/sunstar-foundation/pull/208

**Comment by ehrro** [comment]
Hello @shrotia my bad.

The form-container has a specific width on sunstar.com I thought it was narrower but it's not.

Is it possible to implement the same size as on sunstar.com?

Thanks a lot.

**Comment by shrotia** [comment]
> form-container

yes, I can introduce another variant. The width of the was increased as [part of PR](https://github.com/hlxsites/sunstar-foundation/pull/106) for [this page](https://main--sunstar-foundation--hlxsites.hlx.live/en/awards/perio-link/submit-your-video)

**Comment by shrotia** [comment]
@ehrro introduced Narrower variant for Forms - [Library Link](https://issue-206--sunstar-foundation--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/forms&index=1)

Please have a look at the PR and let me know if there is any other variant/change from sunstar.com needs to be ported in sunstar-foundation?
