### ISSUE TITLE
/award/world-dental-hygienist doesn't look right

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/sunstar-foundation#207]
<img width="1596" alt="Screenshot 2024-02-12 at 10 46 09" src="https://github.com/hlxsites/sunstar-foundation/assets/226514/cf17a796-da63-4ae6-b02f-45f17ef3bdb5">

**Comment by jindaliiita** [comment]
Issue was in the doc, corrected
https://main--sunstar-foundation--hlxsites.hlx.live/award/world-dental-hygienist
