### ISSUE TITLE
Open link in new tab logic

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar-foundation#214]
Hello team there is a new logic for sunstar-foundation.org. They want to open links that go to /en or /dentistry to a new window. Is it possible to implement this logic globally?

**Comment by shrotia** [comment]
@ehrro  just to confirm, If a user is already browsing the "/dentistry" section and clicks on another page within that section, do we still want to open it in a new tab/window? Just need to clarify the expectations here to ensure we implement the desired behavior correctly across the website. Thanks!

**Comment by ehrro** [comment]
Hello @shrotia. No only from main site. If they are in dentistry then it opens in the same window.
