### ISSUE TITLE
Links in nav doc go to the wrong location

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/sunstar-foundation#217]
The links in the [nav doc](https://sunstarsuisse.sharepoint.com/:w:/r/sites/GlobalSunstarWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B0FE26F31-194F-4E52-905F-68452F027D98%7D&file=nav.docx&action=default&mobileredirect=true) don't seem me. For e.g there is one set as https://main--sunstar--hlxsites.hlx.page/

**Comment by shrotia** [comment]
Links on nav page looks fine to me, resolving the ticket. 
![image](https://github.com/hlxsites/sunstar-foundation/assets/119420493/8cabeb71-9fdf-4fa7-b248-25a6823cdf68)
