### ISSUE TITLE
Lay out cards in rows of 4

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/sunstar-foundation#22]
Affected pages are the 'past events links' at the bottom, like these ones:

* https://main--sunstar-foundation--hlxsites.hlx.live/en/awards/awards-photo-gallery/1107
* https://main--sunstar-foundation--hlxsites.hlx.live/en/education/jsdei/gallery/282

**Comment by dnbute** [comment]
Some quick thoughts, should we maybe update the authoring experience to be `column-like` as in trying to get a somewhat what-you-see-is-what-you-get experience, or do we value consistency between the different page suites?

If we keep the authoring experience as is, I'd say have 2 variants, `3-count` and `4-count`, with one of the being the default, whichever is present in more places

**Comment by bosschaert** [comment]
Done
