### ISSUE TITLE
'Breadcrumb' as page title

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/sunstar-foundation#220]
I noticed that the https://main--sunstar-foundation--hlxsites.hlx.live/dentistry page shows as title 'Breadcrumb' whereas it should be `サンスター財団附属千里歯科診療所 | 一般財団法人 サンスター財団` - this is caused by missing metadata in the worddoc.

<img width="1290" alt="Screenshot 2024-02-14 at 09 51 57" src="https://github.com/hlxsites/sunstar-foundation/assets/226514/51a45087-9496-49ef-9038-e68934830fd4">

Are there other pages where the title metadata is missing?

**Comment by shrotia** [comment]
This ticket can be marked closed after the confirmation with the project team https://adobe-dx-support.slack.com/archives/C051MV16P0D/p1707923395597209?thread_ts=1707918175.103819&cid=C051MV16P0D
