### ISSUE TITLE
Content upload

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/sunstar-foundation#51]
This task is logged to upload the following content (discovered by the crawler) to Sharepoint

**PDF**
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/education/jsdei/program2017_shanghai.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/dentistry/index/pdf_safetymanagement.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/grants/research-report/research-report01/pdf_report01mizutani.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/grants/research-report/research-report01/pdf_report02fukui.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/grants/research-report/research-report01/pdf_report03akiyama.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/grants/research-report/research-report01/pdf_reportall01.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/grants/research-report/research-report02/pdf_report01satake.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/grants/research-report/research-report02/pdf_report02katagiri.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/grants/research-report/research-report02/pdf_report03fujisaka.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/grants/research-report/research-report02/pdf_reportall02.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/grants/research-report/research-report03/pdf_reportall01kushumoto.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/grants/research-report/research-report03/pdf_reportall01shatou.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/grants/research-report/research-report03/pdf_reportall03-01.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-autism01.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-card.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-card01.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-card02.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-card03.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-card04.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-finish.pdf
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-video.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2021/05/entrysheet.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2021/05/event_060202.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2022/01/2022_guidance.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2022/02/agreement.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_about.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_guidance-1.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_sheet_01.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_sheet_02.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_sheet_03.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style01.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style02.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style03.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style04.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style05.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style06.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style07.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style08.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style09.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style10.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style11.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style12.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style13.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style14.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style15.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style16.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style17.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/02/2023_apply.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/07/r2_b_2022.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/08/202308_research.pdf
https://www.sunstar-foundation.org/wp-content/uploads/2023/11/202311_research.pdf

**Videos**
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/about-us/hiroo-kaneda-grant/movie/Corporate-Motto.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/about-us/history/movie/Corporate-Motto.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1a_1b_william_giannobile_1.33325.12.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1a_kennethkomman_1.33325.12.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1b_caula.33325.12.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1b_maurizio_tonetti.33325.12.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1c_jeffcoat.33325.12.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1c_tan.33325.12.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/education/jsdei/video_frankfurt2014.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/education/jsdei/video_geneva2012.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/education/jsdei/video_milan2013.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/index/movie/educational_film.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/about-us/activity/aboutus_jyosei.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/about-us/activity/aboutus_rinen.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/about-us/activity/aboutus_senri.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/about-us/history/movie/Corporate-Motto.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/for-healthcare-info/movie/CCC_OralHealth_J_Expert_20MBit_v02.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/for-healthcare-info/movie/CCC_OralHealth_J_Genaral_20MBit_v02.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/for-healthcare-info/movie/movie_section-healthcare02_2020.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-child01.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-child02.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-oral-flail.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-video01.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-video02.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-video03.mp4

**Doc**
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style01.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style02.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style05.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style06.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style07.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style08.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style09.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style10.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style11.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style12.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style13.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style14.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style15.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style16.docx
https://www.sunstar-foundation.org/wp-content/uploads/2023/01/2023_style17.docx

**Images**
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1149.jpg
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1155.jpg
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1159.jpg
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1164.jpg
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1185.jpg
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1192.jpg
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1197.jpg
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1205.jpg
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1456.jpg
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1461.jpg
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1484.jpg
https://www.sunstar-foundation.org/en/wp-content/uploads/2022/06/L0A1488.jpg

**Comment by sdmcraft** [comment]
@ehrro , is there an AEM Assets CS instance where these assets can be uploaded? 
Some of the videos are long and we also have doc files (likely to be served as attachments).

**Comment by bosschaert** [comment]
Meeting discussion: Consider adding redirects for changed URLs.

**Comment by sdmcraft** [comment]
**Videos Upload**
Total 25 videos
Successfully published 5
Unsuccessful 20 (likely all of them are > 2 mins duration)

**Here's the list which were published**
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/about-us/activity/aboutus_senri.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/about-us/activity/aboutus_rinen.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/about-us/activity/aboutus_jyosei.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-video01.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar-en/lib/img/index/movie/educational_film.mp4

**Here's the list which were not published**
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/about-us/hiroo-kaneda-grant/movie/Corporate-Motto.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/about-us/history/movie/Corporate-Motto.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/education/jsdei/video_geneva2012.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/education/jsdei/video_milan2013.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/education/jsdei/video_frankfurt2014.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1a_kennethkomman_1.33325.12.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1c_tan.33325.12.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1c_jeffcoat.33325.12.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1b_caula.33325.12.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1b_maurizio_tonetti.33325.12.mp4
https://www.sunstar-foundation.org/en/wp-content/themes/wp-sunstar-en/lib/img/awards/world-perio/videos/sunstar1a_1b_william_giannobile_1.33325.12.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/about-us/history/movie/Corporate-Motto.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-video02.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-video03.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-oral-flail.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-child01.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/oral-care/advice-child02.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/for-healthcare-info/movie/movie_section-healthcare02_2020.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/for-healthcare-info/movie/CCC_OralHealth_J_Expert_20MBit_v02.mp4
https://www.sunstar-foundation.org/wp-content/themes/wp-sunstar/lib/img/for-healthcare-info/movie/CCC_OralHealth_J_Genaral_20MBit_v02.mp4

Copying @bosschaert @ehrro

**Comment by sdmcraft** [comment]
**PDFs Upload**
Total 51
Successfully published 51
