### ISSUE TITLE
Home page reference in Breadcrumb shows wrong language

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/sunstar-foundation#79]
On Japanese pages, the 'Home' page in the breadcrumb shows up as 'Home' in English, instead of in the Japanese language.

Original:
<img width="598" alt="Screenshot 2024-01-08 at 10 13 30" src="https://github.com/hlxsites/sunstar-foundation/assets/226514/0e5c7020-f399-46b5-bfd1-95e42e0aaeb7">

HLX:
<img width="589" alt="Screenshot 2024-01-08 at 10 13 42" src="https://github.com/hlxsites/sunstar-foundation/assets/226514/dbceaa7c-48e8-4c07-8927-e5b2feb25977">

**Comment by jindaliiita** [comment]
Added text to placeholders.json.
Now, its working fine.
https://main--sunstar-foundation--hlxsites.hlx.live/newsroom/1655
