### ISSUE TITLE
Japanese pages: nav items in header different

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/sunstar-foundation#80]
Original:
<img width="799" alt="Screenshot 2024-01-08 at 10 18 32" src="https://github.com/hlxsites/sunstar-foundation/assets/226514/737c4739-ab20-4936-ac90-cbc87289bb9c">

Hlx:
<img width="668" alt="Screenshot 2024-01-08 at 10 18 39" src="https://github.com/hlxsites/sunstar-foundation/assets/226514/c3c73250-e945-44b5-a07f-084d6274a0f7">

**Comment by jindaliiita** [comment]
Assigning it to @hparwani2

**Comment by hparwani2** [comment]
nav-tree.json wasn't published. it's replicated now.
