### ISSUE TITLE
News article date on Japanese news pages not in muted colours

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/sunstar-foundation#82]
Original:
<img width="405" alt="Screenshot 2024-01-08 at 14 33 47" src="https://github.com/hlxsites/sunstar-foundation/assets/226514/2287a8d5-57f4-441e-b2d3-afb4ed45cc00">

Hlx:
<img width="262" alt="Screenshot 2024-01-08 at 14 33 55" src="https://github.com/hlxsites/sunstar-foundation/assets/226514/48852085-0e65-40f9-98fe-601bf4126e2d">

**Comment by jindaliiita** [comment]
@bosschaert i think this is correct as per the Accessibility.

**Comment by bosschaert** [comment]
@jindaliiita thanks but then the English news pages are wrong 😉 e.g. https://main--sunstar-foundation--hlxsites.hlx.page/en/newsroom/737 so maybe it should be changed that it doesn't happen there either (it's a global CSS change).

**Comment by jindaliiita** [comment]
Heading in page https://main--sunstar-foundation--hlxsites.hlx.page/newsroom/1847 and https://main--sunstar-foundation--hlxsites.hlx.page/en/newsroom/737 is different, one is h1 and other is h2.
And For h2 it picks css style "main .section.newsarticle div h2 + p" to display color light grey. In my opinion heading tag show be same for both the pages

**Comment by bosschaert** [comment]
Thanks @jindaliiita I've changed the English news pages to be based on h1 so that all is consistent. Closing this issue now as completed.
