### ISSUE TITLE
Newsroom has some missing images

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/sunstar-foundation#95]
URL: https://main--sunstar-foundation--hlxsites.hlx.page/en/newsroom

<img width="977" alt="Screenshot 2024-01-11 at 09 46 07" src="https://github.com/hlxsites/sunstar-foundation/assets/226514/9769c8cf-a3f3-4aa9-89f9-06b0cf79ab81">

**Comment by meejain** [comment]
This has been taken care. The default image has been successfully previewed & published in the sharepoint.
